### ISSUE TITLE
Algorithmic layouts

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#485] opened 2016-03-13 21:06 UTC
I'm interested in creating maps from an external app, using the emerging token based API.  I don't want to specify layout; ideally I'd like the map laid out in a sensible and pleasing way.

@Connoropolous you mentioned elsewhere that there is an auto-layout algorithm that places new nodes in a spiral?  How could I see this in action, or where to look in the code?

Any thoughts on more sophisticated auto-layouts like force directed layouts?

**Comment by Connoropolous** [comment] 2016-03-13 21:36
The `arranged` column on the maps table was intended for use for this. the idea being that if a map is not marked as `arranged` then we would use a force directed algo to lay it out. We use to have it working like that actually, but the force directed algorithm the Javascript InfoVis toolkit was using was not very satisfactory, so we disabled the feature. 

Perhaps we could have a function for now, written in the backend, which lays out a map with a force-directed algorithm.  The front end wouldn't have to worry about it. And you could trigger the function to be called by hitting an API endpoint related to that map. 

Do you know about how we use `mappings` in metamaps to associate topics and synapses to maps? It is on mappings that we store the x and y positions of topics on maps

**Comment by Connoropolous** [comment] 2016-03-13 21:41
Basically, the only time we do 'auto-layout' stuff is when we pull a topic into a map from the upper left search results pane, because the user wouldn't have specified a X-Y location on the map for it. That is implemented here: 
https://github.com/metamaps/metamaps_gen002/blob/develop/app/assets/javascripts/src/Metamaps.js.erb#L4174

which calls
https://github.com/metamaps/metamaps_gen002/blob/develop/app/assets/javascripts/src/Metamaps.js.erb#L4526

**Comment by Connoropolous** [comment] 2016-03-13 21:44
This would also tie in quite well to the work on importing topics via a spreadsheet. It's very unlikely that you want to specify the coordinates within the spreadsheet, so would obviously hope for auto layout stuff to happen 
https://github.com/metamaps/metamaps_gen002/issues/475

**Comment by harlantwood** [comment] 2016-03-14 16:00
Thanks for your thoughtful answer @Connoropolous!

I love the idea of a force directed layout computed on the backend...

**Closed** 2017-01-14 08:15 UTC
